import "~/src/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import { TRPCReactProvider } from "~/src/trpc/react";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body className="flex flex-col min-h-screen w-screen">
				<SessionProvider>
					<Header />
					<main className="flex-grow flex items-center justify-center w-full px-4 bg-gray-100">
						<TRPCReactProvider>{children}</TRPCReactProvider>
					</main>
					<Footer />
				</SessionProvider>
			</body>
		</html>
	);
}
